version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - "27018:27018"
  